

CREATE TABLE DIMENSION_TABLE1 (
    SAMPLINGPOINTNOTATION VARCHAR(50) PRIMARY KEY,
    SAMPLINGPOINTLABEL VARCHAR(50),
    SAMPLINGPOINTEASTING NUMBER,
    SAMPLINGPOINTNORTHING NUMBER
);

CREATE TABLE DIMENSION_TABLE2  (
    DETERMINANT_NOTATION VARCHAR(50) PRIMARY KEY,
    DETERMINANT_DEFINITION VARCHAR(255),
    DETERMINANT_UNIT VARCHAR(50)
);

CREATE TABLE DIMENSION_TABLE3 (
    SAMPLEPURPOSEID INT PRIMARY KEY,
    SAMPLEPURPOSELABEL VARCHAR(100),
    SAMPLEMATERIALTYPE VARCHAR(50)
);

CREATE TABLE DIMENSION_TABLE4 (
    TIMEID INT PRIMARY KEY,
    SAMPLEDATE DATE,
    SAMPLETIME VARCHAR2(10),
    SAMPLEYEAR NUMBER, 
    SAMPLEMONTH NUMBER, 
    SAMPLEWEEK NUMBER, 
    SAMPLEDAY NUMBER
);


