CREATE TABLE FACT_TABLE (
    MEASUREMENT_ID VARCHAR2(255) PRIMARY KEY,
    SAMPLINGPOINTNOTATION VARCHAR2(255),
    DETERMINANT_NOTATION VARCHAR2(50),
    PURPOSE_ID NUMBER(38,0),
    TIME_ID NUMBER(38,0),
    FACT_RESULT FLOAT
);

CREATE TABLE FACT_TABLE (
    MEASUREMENT_ID VARCHAR(100) PRIMARY KEY,
    SAMPLINGPOINTNOTATION VARCHAR2(50),
    DETERMINANT_NOTATION VARCHAR2(50),
    PURPOSE_ID NUMBER,
    TIME_ID NUMBER,
    FACT_RESULT FLOAT,
    CONSTRAINT fk_sampling_point FOREIGN KEY (SAMPLINGPOINTNOTATION) REFERENCES DIMENSION_TABLE1(SAMPLINGPOINTNOTATION),
    CONSTRAINT fk_time FOREIGN KEY (TIME_ID) REFERENCES DIMENSION_TABLE4(TIMEID),
    CONSTRAINT fk_purpose FOREIGN KEY (PURPOSE_ID) REFERENCES DIMENSION_TABLE3(SAMPLEPURPOSEID),
    CONSTRAINT fk_determinand FOREIGN KEY (DETERMINANT_NOTATION) REFERENCES DIMENSION_TABLE2(DETERMINANT_NOTATION)
);



INSERT INTO FACT_TABLE(MEASUREMENT_ID, SAMPLINGPOINTNOTATION, DETERMINANT_NOTATION, PURPOSE_ID, TIME_ID, FACT_RESULT)
 
SELECT
 
    s.ID,
 
    d1.SAMPLINGPOINTNOTATION,
 
    d2.DETERMINANT_NOTATION,
 
    d3.SAMPLEPURPOSEID,
    
    d4.TIMEID,
 
    s."result"
 
FROM SOURCE_TABLE s
 
LEFT JOIN DIMENSION_TABLE1 d1 ON d1.SAMPLINGPOINTNOTATION = s.SAMPLING_POINT_NOTATION
 
LEFT JOIN DIMENSION_TABLE2 d2 ON d2.DETERMINANT_NOTATION = s.DETERMINAND_NOTATION
 
LEFT JOIN DIMENSION_TABLE4 d4 ON d4.SAMPLEDATE = s.SAMPLE_DATE AND d4.SAMPLETIME = s.SAMPLE_TIME
 
LEFT JOIN DIMENSION_TABLE3 d3 ON d3.SAMPLEPURPOSELABEL = s.SAMPLE_PURPOSE_LABEL AND d3.SAMPLEMATERIALTYPE = s.SAMPLED_MATERIAL_TYPE;






